url="https://blog.5-23.dev/p/{starix.id}/"
thumb="https://blog.5-23.dev/p/{starix.id}/thumb.jpg"
name="Asta blog"
avatar="https://avatars.githubusercontent.com/u/86705803?v=4"

[post]
content="@everyone `{starix.id}`가 올라왔어요!"
color="#2E7EFF"

[fix]
content=""
color="#FF782E"
